### ISSUE TITLE
Charity stakeholder

### ISSUE THREAD

**Issue by RamyAlshurafa** [RamyAlshurafa/AniFlix#1]
#### Acceptance criteria:
- [ ]  As a charity stakeholder, I want to sign up into the website as charity user.
- [ ]  As a charity stakeholder, I want to login into the website.
- [ ]  As a charity stakeholder, I want to view my profile
- [ ]  As a charity stakeholder, I want to edit my profile
- [ ]  As a charity stakeholder, I want to view my dashboard.
- [ ]  As a charity stakeholder, I want to view a list of my donation posts.
- [ ]  As a charity stakeholder, I want to view the details of each post in a single page.
- [ ]  As a charity stakeholder, I want to comment and reply on the donation post.
- [ ]  As a charity stakeholder, I want to dis-active or reactivate the donation post.
- [ ]  As a charity stakeholder, I want to see the donors list.
- [ ]  As a charity stakeholder, I want to send thank-you-email to the donors.
- [ ]  As a charity stakeholder, I want to create a new donation post.
- [ ]  As a charity stakeholder, I want to edit an existing donation post.
- [ ]  As a charity stakeholder, I want to send an invitation for donation.
