### ISSUE TITLE
Dis-active or reactivate the donation post

### ISSUE THREAD

**Issue by RamyAlshurafa** [RamyAlshurafa/AniFlix#10]
### As a charity stakeholder I want to dis-active or reactivate the donation post.
Relates #1

#### Acceptance criteria:

- [ ] When I view the post  I can “ Activate” or “Dis-activate” the post depending on its status
- [ ] When I dis-active the post I won't the post to be shown to users.
- [ ] When I reactivate the post I want the post to be shown again to users.
