### ISSUE TITLE
Donors list page

### ISSUE THREAD

**Issue by RamyAlshurafa** [RamyAlshurafa/AniFlix#11]
### As a charity stakeholder I want to see the donors list.
Relates #1

#### Acceptance criteria:
- [ ] When I’m in my dashboard I want a button to redirect me to ‘donors’ page.
- [ ] When I’m in the donors' page I want to view the donors' brief information [name, donation value, on which post he has donated].
- [ ] When I’m in donors list I want to see the statistics of donors.
- [ ] When I’m in donors list I can sort donors regarding the post they have donated for.
