### ISSUE TITLE
Sending thank-you-email to the donors

### ISSUE THREAD

**Issue by RamyAlshurafa** [RamyAlshurafa/AniFlix#12]
### As a charity stakeholder I want to send thank-you-email to the donors.
Relates #1

#### Acceptance criteria:

- [ ] When I visit the donors' list I can send a thank-you-email for each, So I can fill up the emailing form with a customized message or I send the default one.
- [ ] When I visit the donors' list I can send a thank-you-email for all at once, , So I can fill up the emailing form with a customized message or I send the default one.
- [ ] When I visit the donors' list I can select some donors to send them thank-you-email at once, So I can fill up the emailing form with a customized message or I send the default one.
