### ISSUE TITLE
Create a new donation post

### ISSUE THREAD

**Issue by RamyAlshurafa** [RamyAlshurafa/AniFlix#13]
### As a charity stakeholder I want to create a new donation post.
Relates #1

#### Acceptance criteria:

- [ ] When I’m in my dashboard I want to see “create new post” button, so it will redirect me to “new post” page
- [ ] When I’m in “new post” page I want to fill up the post’s form,
- [ ] When I’m filling new post’s form and make something wrong I want it to warn me.
- [ ] When I successfully filled the form and click on submit I want it to redirect me to view the post in a single page.
