### ISSUE TITLE
Edit donation post

### ISSUE THREAD

**Issue by RamyAlshurafa** [RamyAlshurafa/AniFlix#14]
### As a charity stakeholder, I want to edit an existing donation post.
Relates #1

#### Acceptance criteria:

- [ ] When I click on “edit” button in any page e.g.[single post page, post list,…], I want to change any of post information.
- [ ] When I’m editing the post and make something wrong I want it to warn me.
- [ ] When I successfully edited the post and click on submit I want it to redirect me to view the post in a single page.
