### ISSUE TITLE
Sign up

### ISSUE THREAD

**Issue by RamyAlshurafa** [RamyAlshurafa/AniFlix#2]
### As a charity stakeholder, I want to sign up on the website as a charity user.
Relates #1 
#### Acceptance criteria:
- [ ] When I visit the website homepage I want to find a “sign up as Charity” button to redirect me to sign up page.
- [ ] When I’ve redirected to “sign up” page I want to fill up a form with my information.
- [ ] When I filled something wrong I want to know what's wrong in this field, so I can edit it before submitting.
- [ ] When I click on submit I want to redirect me to my dashboard.
