### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by RamyAlshurafa** [RamyAlshurafa/AniFlix#3]
### As a charity stakeholder, I want to login to the website.
Relates #1

#### Acceptance criteria:
- [ ] When I visit any route of the website (except login and sign up pages) and I’m not logged in yet I want to redirect me to the login page.
- [ ] When I successfully filled my username and password and I clicked on “login” I want to redirect me to my dashboard.
- [ ] when I fill up a wrong password or username I want to show me that’s “invalid password or username”.
- [ ] When I visit any route of the website and I’m already logged in I want to access that route.
