### ISSUE TITLE
View profile page

### ISSUE THREAD

**Issue by RamyAlshurafa** [RamyAlshurafa/AniFlix#4]
### As a charity stakeholder I want to view my profile
Relates #1

#### Acceptance criteria:
- [ ] When I visit “my profile” page I want to view my information and details about myself as a page owner.
- [ ] When I’m in my profile I want to notify me If my information is incomplete, so I can complete them
- [ ] When I’m in my profile I want to view the notifications and messages at the header of the page.
