### ISSUE TITLE
Profile Editing

### ISSUE THREAD

**Issue by RamyAlshurafa** [RamyAlshurafa/AniFlix#5]
### As a charity stakeholder I want to edit my profile
Relates #1

#### Acceptance criteria:

- [ ] When I’m in my profile I want to find an “Edit my profile” button, so it will redirect me to “editing” page.
- [ ] When I’m in “Editing” page I can easily view my current information an change any of them.
- [ ] When I’m editing my information and fill up something wrong I need it to warn me.
- [ ] When I finish editing my information I want to save my changes.
- [ ] After saving my changes I want it to redirect me to my profile page to view the changes.
