### ISSUE TITLE
View dashboard page

### ISSUE THREAD

**Issue by RamyAlshurafa** [RamyAlshurafa/AniFlix#6]
### As a charity stakeholder, I want to view my dashboard.
Relates #1

#### Acceptance criteria:
- [ ] When I visit “my dashboard” I want to view the general statistics of donations.
- [ ] When I visit “my dashboard” I want to view my notification and messages.
- [ ] When I visit “my dashboard” I want to find a menu with options e.g (view donation list, create new donation, etc… )
