### ISSUE TITLE
View a list of donation posts.

### ISSUE THREAD

**Issue by RamyAlshurafa** [RamyAlshurafa/AniFlix#7]
### As a charity stakeholder I want to view a list of my donation posts.
Relates #1
#### Acceptance criteria:
- [ ] When I visit “donation list” I want to see a list of all my posts,
- [ ] When I visit “donation list” I want to see brief details of each post (title, donation value, status).
- [ ] When I visit “donation list” I want to see [ view, edit, and delete] buttons beside each.
