### ISSUE TITLE
View each post in a single page.

### ISSUE THREAD

**Issue by RamyAlshurafa** [RamyAlshurafa/AniFlix#8]
### As a charity stakeholder I want to view the details of each post in a single page.
Relates #1

#### Acceptance criteria:
- [ ] When I view the post single page I want to see all of the post’s information.
- [ ] When I view the post single page I want to see the statistics of the post.
- [ ] When I view the post single page I want to see [ edit, delete] buttons.
- [ ] When I view the post single page I want to see “send invitation email” form.
